name: Sync and Build Upstream

on:
  schedule:
    - cron: '0 1 * * *' # Kj√∏rer kl 01:00 hver dag
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync upstream changes
        id: sync
        uses: a28781234/sync-upstream-repo@v1.2.1
        with:
          upstream_repository: nightscout/AndroidAPS
          upstream_branch: master
          target_branch: master
          force: false # Sett til true hvis du vil overskrive egne endringer
