name: Sync updstream

on:
  schedule:
    - cron: '0 0 * * *' # Kj√∏rer hver natt
  workflow_dispatch:    # Lar deg starte manuelt

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork with Upstream
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/merge-upstream \
            -d '{"branch":"master"}'
